# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FCFS import Ui_FCFS
from Priority import Ui_Priority
from RR import Ui_RR
from SJF import Ui_SJF



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FCFS = QtWidgets.QPushButton(self.centralwidget)
        self.FCFS.setGeometry(QtCore.QRect(300, 130, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.FCFS.setFont(font)
        self.FCFS.setObjectName("FCFSBtn")
        self.FCFS.clicked.connect(self.open_FCFS_info)
        self.SJF = QtWidgets.QPushButton(self.centralwidget)
        self.SJF.setGeometry(QtCore.QRect(300, 210, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.SJF.setFont(font)
        self.SJF.setObjectName("SJFBtn")
        self.SJF.clicked.connect(self.open_SJF_non_info)
        self.Priority = QtWidgets.QPushButton(self.centralwidget)
        self.Priority.setGeometry(QtCore.QRect(300, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Priority.setFont(font)
        self.Priority.setObjectName("PriorityBtn")
        self.Priority.clicked.connect(self.open_Priority_preem_info)
        self.RR = QtWidgets.QPushButton(self.centralwidget)
        self.RR.setGeometry(QtCore.QRect(300, 370, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.RR.setFont(font)
        self.RR.setObjectName("RRBtn")
        self.RR.clicked.connect(self.open_RR_info)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 771, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scheduling Algorithms"))
        self.FCFS.setText(_translate("MainWindow", "First Come First Serve"))
        self.SJF.setText(_translate("MainWindow", "Shortest Job First"))
        self.Priority.setText(_translate("MainWindow", "Priority Based"))
        self.RR.setText(_translate("MainWindow", "Round-Robin"))
        self.label.setText(_translate("MainWindow", "CPU SCHEDULING ALGORITHMS "))

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

    def open_FCFS_info(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_FCFS()
        self.ui.setupUi(self.window)
        first.hide() 
        self.window.show()

    def open_SJF_non_info(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SJF()
        self.ui.setupUi(self.window)
        first.hide() 
        self.window.show()
    
    def open_RR_info(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RR()
        self.ui.setupUi(self.window)
        first.hide() 
        self.window.show()
        
    def open_Priority_preem_info(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Priority()
        self.ui.setupUi(self.window)
        first.hide() 
        self.window.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    first = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(first)
    first.show()
    sys.exit(app.exec_())
